### ISSUE TITLE
Chinese charset issue

### ISSUE THREAD

**Issue by LianYangCn** [Tarferi/Starcraft-Translation-Tool#2]
Hello @Tarferi, I use (TranslationUI) [https://github.com/Tarferi/Starcraft-Translation-Tool/releases/tag/2034863] to make a Chinese map normally, but some characters in normal use are normal, But some other characters become "??"

if you can disclose more details about TranslateLib.dll, I can also help debug

![9b26d0fbf126cb5f7b9d5a651237798](https://user-images.githubusercontent.com/13026006/82108812-f3704880-9763-11ea-95de-3f63d8efe64e.png)

**Comment by Tarferi** [comment]
The dll file doesn't work with strings. It uses raw bytes as those are received encoded from UI. 
That said, I may only add encoding selection for every language set. It won't do much if there is no support in SC:R though. Can you provide the exact string that causes the issue?

**Comment by LianYangCn** [comment]
I can provide but how?  You mean this:
The Doomed Quest: 五位英雄被派去了 Doomed Quest, 尽管存在着古老的诅咒，他们必须利用神殿的力量消灭领主. 一场漫长而坚苦的战斗!

I got something really weird.

When I use this [release](https://github.com/Tarferi/Starcraft-Translation-Tool/releases/tag/2034863), it can generate maps very well.

When I use the program compiled directly from the source code, it cannot generate anything and always prompts that "Translation failed"

**Comment by Tarferi** [comment]
The compilation process differs between debug and release. Debug covers DLL linking during runtime whereas release links in compile time. 
Latest commit contains encoding resolver and forces UTF-8 by default. I also fixed the internal updator, so you should get latest version by that and compare it to your local compilation result.

**Comment by LianYangCn** [comment]
First,
Changes this hard code path suitable
https://github.com/Tarferi/Starcraft-Translation-Tool/blob/3ea67679c3662fef5db87e9cd2984def65efee90/TheLib.cs#L120




Then,
1. Debug/Release can NOT create .smt, and prompts that "Failed to create settings file"
2. The setting file saved before, it can't be translated either. 

https://github.com/Tarferi/Starcraft-Translation-Tool/blob/3ea67679c3662fef5db87e9cd2984def65efee90/TheLib.cs#L93

always get 0x02 here.




BTW, updator works

**Comment by Tarferi** [comment]
The DLL should never return 0x02 in result byte. It returns unchanged value in case of success.
Failure in creation was caused by missing fields in new settings format (encoding array was null). The setting files saved prior this update should fall into the vanilla loader branch
https://github.com/Tarferi/Starcraft-Translation-Tool/blob/3ea67679c3662fef5db87e9cd2984def65efee90/Settings.cs#L62

If you do have an example setting file that no longer works as expected, please share it.

As for the absolute path, there is no reason not to use memory module as there is no debug version of the library, so that is forced option now.

**Comment by LianYangCn** [comment]
I have Merged every single code from this repo
And clean/rebuild

Everything goes well except for the result of the DLL.
It can NOT generate anything and always prompts that "Translation failed" 

Steps to reproduce：
1. Add Translation， name it to "zhCN"
2. Choose "zhCN" and Run

Enclose the data(.smt and map).
[data.zip](https://github.com/Tarferi/Starcraft-Translation-Tool/files/4639566/data.zip)

Before call DLL
![aaec86182cfa926f20162c6a6ef0305](https://user-images.githubusercontent.com/13026006/82134423-7065f580-982a-11ea-88ff-af8a61c8a4e3.png)

After call DLL
![2595397db7378f7f8aa9a5df2cb45a0](https://user-images.githubusercontent.com/13026006/82134446-91c6e180-982a-11ea-9d2c-2c13b6a34613.png)

**Comment by Tarferi** [comment]
The error is somewhat more complicated. The 0x2 value means that the map file was invalid. After binary inspection of the library runtime data, the extracted CHK did not contain MBRF section.
The exact reason for something like that to happen is within the underlying parser. The map is loaded as partial CHK mode, which means that sections only up to STR and TRIG are loaded. The issue is raised when the MBRF section is required and appears beyond both STR and TRIG sections. I updated the library to cover MBRF in partial load mode.
However, it is unclear which other mechanism breaks upon this extension.

**Comment by LianYangCn** [comment]
Wonderful!
Everything works fine, thank you for your excellent work
